### ISSUE TITLE
Delete a Shopcart Model

### ISSUE THREAD

**Issue by radhikamattoo** [nyu-devops-echo/shopcarts#25]
**As a** developer
**I need** to delete a shopcart model
**So that** I don't have to store it anymore

**Assumptions:** 
* Method in the shopcarts model
* In-memory persistence is fine for now

**Acceptance Criteria:**
```
Given a shopcart model
When I call the delete method on the shopcart model
Then the shopcart should no longer exist in memory
```

**Comment by radhikamattoo** [comment]
Hey @thoughts1053 @carpetri @RegulusXiang I know the acceptance criteria says 'given a shopcart id' we should be able to delete the shopcart model, but the professor's code has deletion as an instance method on a given shopcart (i.e. `cart.delete()` instead of `Shopcart.delete(uid)`). 

Should we change the acceptance criteria for this issue?

**Comment by carpetri** [comment]
Yes, I think we should change the acceptance criteria. @radhikamattoo

**Comment by radhikamattoo** [comment]
Ok! Changed it from `Given a shopcart id` to `Given a shopcart model`

**Comment by thoughts1053** [comment]
Personally, I think we should have kept it the original way. `Shopcart.delete(uid)` makes more sense to me vs having to first find the cart and then calling delete on it. And when using a persistence layer, this is the way I normally do it.

However, let's just keep it this way to follow the Professor's pattern (and since it's already done). 😄
